### ISSUE TITLE
How to customize the breadcrumb separator character?

### ISSUE THREAD

**Issue by marcelocg** [Vimux/Binario#23]
I tried to create a custom css file within the site's `static/css` folder with the following content:

```css
.breadcrumb__item::after {
	display: block;
	margin: 0 .3125rem;
	content: "/";
}
```
This had no effect. What am I missing?

Having the separator character as a configurable param in config.toml would be nice. Could anyone give me some orientation on how could it be implemented?
