### ISSUE TITLE
Mastodon: fix url generation

### ISSUE THREAD

**Issue by jadr2ddude** [Vimux/Binario#8]
Currently, binario makes the assumption that mastodon users use the `mastodon.social` instance. This assumption is incorrect for an estimated 78% of mastodon users. I originally ran into this issue after putting my mastodon username into the config:

```toml
[Params.Social]
  mastodon = "@jadenw@mst3k.interlinked.me"
```

This created a link to: https://mastodon.social/@@jadenw@mst3k.interlinked.me

The correct link would have been: https://mst3k.interlinked.me/@jadenw

Mastodon usernames are structured as follows:
> @_username_@_instance_

And user homepages:
> https://_instance_/@_username_
